[project]
name = 'staking-project'
description = 'STX staking contract'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.staking]
path = 'contracts/staking.clar'
clarity_version = 2
epoch = '2.4'
[repl.analysis]
passes = ['check_checker', 'call_checker']
